### ISSUE TITLE
Failed to run custom build for `ncurses v5.86.0`

### ISSUE THREAD

**Issue by dominikbraun** [aligator/rust-snake#1]
The ncurses crate (v5.68.0 according no `cargo.toml`) won't compile on Windows 10. The newest version (v5.99.0) doesn't work either.

![924757ad-6611-4cbd-b2f8-428bb3b44ff9](https://user-images.githubusercontent.com/36575275/58155531-55db5980-7c74-11e9-86e6-275a4fc6cb9a.jpg)

**Comment by aligator** [comment]
I think https://github.com/TimonPost/crossterm would be a good alternative. I have to look into it.

**Comment by aligator** [comment]
finished
